server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integration?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tmh010625
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      web-stat-filter:
        enabled: true


mybatis-plus:
  type-aliases-package: org.blue.springbootmodular.entity
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
